import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { siteConfig } from '../src/config.js'
import { classifyRepo } from '../src/category-engine.js'
const dataDir = new URL('../public/data/', import.meta.url)
export const paths = { repos: new URL('./repos.json', dataDir), meta: new URL('./meta.json', dataDir), status: new URL('./status.json', dataDir), history: new URL('./history.json', dataDir) }
const configured = siteConfig.githubUsername && siteConfig.githubUsername !== 'demo' ? siteConfig.githubUsername : ''
const username = process.env.GITSTAR_USERNAME || process.env.GITHUB_USERNAME || configured || process.env.GITHUB_REPOSITORY_OWNER || siteConfig.githubUsername; const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || ''
const headers = { Accept: 'application/vnd.github.star+json', 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'GitStar-Sync/2.0' }; if (token) headers.Authorization = `Bearer ${token}`
export function classifyResponse(response) { const remaining = response.headers.get('x-ratelimit-remaining'); return response.status === 429 || (response.status === 403 && (remaining === '0' || response.headers.has('retry-after'))) ? 'rate_limited' : 'error' }
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
export async function fetchStars(fetchImpl = fetch) { const repos = []; let url = `https://api.github.com/users/${encodeURIComponent(username)}/starred?per_page=100`; while (url) { let response; for (let attempt = 0; ; attempt += 1) { try { response = await fetchImpl(url, { headers }); if (response.ok || (response.status < 500 && response.status !== 408)) break } catch (error) { if (attempt >= 2) throw error } if (attempt >= 2) break; await sleep(250 * 2 ** attempt) } if (!response.ok) { const error = new Error(`${classifyResponse(response)}:${response.status}`); error.kind = classifyResponse(response); throw error } repos.push(...await response.json()); url = (response.headers.get('link') || '').match(/<([^>]+)>;\s*rel="next"/)?.[1] || '' } return repos }
export function normalize(raw, overrides = siteConfig.manualCategories) { const repo = raw.repo || raw; const fullName = repo.full_name || ''; return { id: repo.id, full_name: fullName, name: repo.name || fullName.split('/').pop(), owner: repo.owner?.login || fullName.split('/')[0], html_url: repo.html_url || '', homepage: /^https?:\/\//i.test(repo.homepage || '') ? repo.homepage : '', description: repo.description || '', language: repo.language || '', topics: Array.isArray(repo.topics) ? repo.topics : [], stars: repo.stargazers_count || 0, forks: repo.forks_count || 0, pushed_at: repo.pushed_at || null, starred_at: raw.starred_at || null, category: classifyRepo(repo, overrides, siteConfig.categories), archived: Boolean(repo.archived) } }
export const hashRepos = (repos) => createHash('sha256').update(JSON.stringify([...repos].sort((a,b) => a.full_name.localeCompare(b.full_name)))).digest('hex')
async function readJson(url, fallback) { try { return JSON.parse(await readFile(url, 'utf8')) } catch { return fallback } }
function eventFields(repo) { return { full_name: repo.full_name, html_url: repo.html_url, description: repo.description, category: repo.category } }
async function writeSummary(data) { if (process.env.GITHUB_STEP_SUMMARY) await writeFile(process.env.GITHUB_STEP_SUMMARY, `## GitStar sync\n\n- Status: **${data.status}**\n- Repositories: **${data.count}**\n- Added: **${data.added || 0}** · Removed: **${data.removed || 0}**\n- Changed snapshot: **${data.changed ? 'yes' : 'no'}**\n`) }
async function main() { await mkdir(dataDir, { recursive: true }); const previous = await readJson(paths.repos, { repositories: [] }); const oldMeta = await readJson(paths.meta, {}); const oldHistory = await readJson(paths.history, { events: [] }); const attemptedAt = new Date().toISOString(); let rawStars; try { rawStars = await fetchStars() } catch (error) { const status = error.kind || 'error'; await writeFile(paths.status, JSON.stringify({ status, message: error.message, attemptedAt, lastSuccessAt: oldMeta.syncedAt || null }, null, 2) + '\n'); await writeSummary({ status, count: previous.repositories?.length || 0 }); console.warn(`GitStar sync: ${status} (${error.message})`); return }
  const repositories = rawStars.map((repo) => normalize(repo)).sort((a,b) => new Date(b.starred_at || 0) - new Date(a.starred_at || 0)); const hash = hashRepos(repositories); const previousIds = new Set((previous.repositories || []).map((r) => r.full_name)); const currentIds = new Set(repositories.map((r) => r.full_name)); const events = [...repositories.filter((r) => !previousIds.has(r.full_name)).map((r) => ({ type: 'added', ...eventFields(r), at: attemptedAt })), ...(previous.repositories || []).filter((r) => !currentIds.has(r.full_name)).map((r) => ({ type: 'removed', ...eventFields(r), at: attemptedAt }))]; const changed = hash !== oldMeta.hash; const meta = { schemaVersion: 2, username, syncedAt: changed ? attemptedAt : (oldMeta.syncedAt || attemptedAt), checkedAt: attemptedAt, count: repositories.length, hash }
  if (changed) { await writeFile(paths.repos, JSON.stringify({ repositories })); const history = oldMeta.username && oldMeta.username !== username ? events.slice(0, 500) : [...events, ...(oldHistory.events || [])].slice(0, 500); await writeFile(paths.history, JSON.stringify({ events: history }, null, 2) + '\n') }
  await writeFile(paths.meta, JSON.stringify(meta, null, 2) + '\n'); await writeFile(paths.status, JSON.stringify({ status: 'ok', message: '', attemptedAt, lastSuccessAt: attemptedAt }, null, 2) + '\n'); console.log(`${changed ? 'Synced' : 'No changes'} ${repositories.length} starred repositories for @${username}. ${events.length} changes.`); await writeSummary({ status: 'ok', count: repositories.length, added: events.filter((e) => e.type === 'added').length, removed: events.filter((e) => e.type === 'removed').length, changed }) }
if (import.meta.url === `file://${process.argv[1]}`) main().catch((error) => { console.error(error); process.exit(1) })
